#include "pyctpmd.h"
#include "pyctptd.h"

PYBIND11_MODULE(pyctp, m)
{
    m.doc() = "Author:Bohr\nEmail:shiyu.he@jyquant.com.cn\nDate:20210116\n\nClasses:\n  PyMdApi for market data\n  PyTdApi for trading";

    py::class_<PyMdApi, PyMDWrapper> (m, "PyMdApi")
        .def(py::init<>())
        .def("createFtdcMdApi", &PyMdApi::createFtdcMdApi,"创建api",py::arg("pszFlowPath")="")
        .def("release", &PyMdApi::release,"不再使用本接口对象时,调用该函数删除接口对象")
        .def("init", &PyMdApi::init,"初始化运行环境,只有调用后,接口才开始工作")
        .def("join", &PyMdApi::join,"等待接口线程结束运行")
        .def("exit", &PyMdApi::exit,"退出")
        .def("GetApiVersion", &PyMdApi::GetApiVersion,"获取到的版本号")
        .def("getTradingDay", &PyMdApi::getTradingDay,"获取当前交易日")
        .def("registerFront", &PyMdApi::registerFront,"注册前置机网络地址",py::arg("pszFrontAddress")="")
        .def("subscribeMarketData", &PyMdApi::subscribeMarketData,"订阅行情",py::arg("instrumentID"))
        .def("unSubscribeMarketData", &PyMdApi::unSubscribeMarketData,"退订行情",py::arg("instrumentID"))
        .def("subscribeForQuoteRsp", &PyMdApi::subscribeForQuoteRsp,"订阅询价",py::arg("instrumentID"))
        .def("unSubscribeForQuoteRsp", &PyMdApi::unSubscribeForQuoteRsp,"退订询价",py::arg("instrumentID"))
        .def("reqUserLogin", &PyMdApi::reqUserLogin,"发起登录请求",py::arg("req"),py::arg("reqid"))
        .def("reqUserLogout", &PyMdApi::reqUserLogout,"发出登出请求",py::arg("req"),py::arg("reqid"))
        .def("OnFrontConnected", &PyMdApi::OnFrontConnected,"当客户端与交易后台建立起通信连接时（还未登录前），该方法被调用")
        .def("OnFrontDisconnected", &PyMdApi::OnFrontDisconnected,"当客户端与交易后台通信连接断开时，该方法被调用。当发生这个情况后，API会自动重新连接，客户端可不做处理",py::arg("nReason"))
        .def("OnHeartBeatWarning", &PyMdApi::OnHeartBeatWarning,"心跳超时警告。当长时间未收到报文时，该方法被调用。",py::arg("nTimeLapse"))
        .def("OnRspUserLogin", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyMdApi::OnRspUserLogin),"登录请求响应",py::arg("RspUserLogin"),py::arg("RspInfo"),py::arg("nRequestID"),py::arg("last"))
        .def("OnRspUserLogout", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyMdApi::OnRspUserLogout),"登出请求响应",py::arg("pUserLogout"),py::arg("RspInfo"),py::arg("nRequestID"),py::arg("last"))
        .def("OnRspError", py::overload_cast<const py::dict &, int, bool>(&PyMdApi::OnRspError),"错误应答",py::arg("RspInfo"),py::arg("nRequestID"),py::arg("last"))
        .def("OnRspSubMarketData", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyMdApi::OnRspSubMarketData),"订阅行情应答",py::arg("SpecificInstrument"),py::arg("RspInfo"),py::arg("nRequestID"),py::arg("last"))
        .def("OnRspUnSubMarketData", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyMdApi::OnRspUnSubMarketData),"取消订阅行情应答",py::arg("SpecificInstrument"),py::arg("RspInfo"),py::arg("nRequestID"),py::arg("last"))
        .def("OnRspSubForQuoteRsp", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyMdApi::OnRspSubForQuoteRsp),"订阅询价应答",py::arg("SpecificInstrument"),py::arg("RspInfo"),py::arg("nRequestID"),py::arg("last"))
        .def("OnRspUnSubForQuoteRsp", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyMdApi::OnRspUnSubForQuoteRsp),"取消订阅询价应答",py::arg("SpecificInstrument"),py::arg("RspInfo"),py::arg("nRequestID"),py::arg("last"))
        .def("OnRtnDepthMarketData", py::overload_cast<const py::dict &>(&PyMdApi::OnRtnDepthMarketData),"深度行情通知",py::arg("DepthMarketData"))
        .def("OnRtnForQuoteRsp", py::overload_cast<const py::dict &>(&PyMdApi::OnRtnForQuoteRsp),"询价通知",py::arg("ForQuoteRsp"));

    py::class_<PyTdApi,PyTdWrapper>(m,"PyTdApi")
        .def(py::init<>())
        .def("createFtdcTraderApi", &PyTdApi::createFtdcTraderApi)
        .def("release", &PyTdApi::release)
        .def("init", &PyTdApi::init)
        .def("join", &PyTdApi::join)
        .def("exit", &PyTdApi::exit)
        .def("GetApiVersion", &PyTdApi::GetApiVersion)
        .def("getTradingDay", &PyTdApi::getTradingDay)
        .def("registerFront", &PyTdApi::registerFront)
        .def("subscribePublicTopic", &PyTdApi::subscribePublicTopic)
        .def("subscribePrivateTopic", &PyTdApi::subscribePrivateTopic)

        .def("reqAuthenticate", &PyTdApi::reqAuthenticate)
        .def("reqUserLogin", &PyTdApi::reqUserLogin)
        .def("reqUserLogout", &PyTdApi::reqUserLogout)
        .def("reqUserPasswordUpdate", &PyTdApi::reqUserPasswordUpdate)
        .def("reqTradingAccountPasswordUpdate", &PyTdApi::reqTradingAccountPasswordUpdate)
        .def("reqUserAuthMethod", &PyTdApi::reqUserAuthMethod)
        .def("reqGenUserCaptcha", &PyTdApi::reqGenUserCaptcha)
        .def("reqGenUserText", &PyTdApi::reqGenUserText)
        .def("reqUserLoginWithCaptcha", &PyTdApi::reqUserLoginWithCaptcha)
        .def("reqUserLoginWithText", &PyTdApi::reqUserLoginWithText)
        .def("reqUserLoginWithOTP", &PyTdApi::reqUserLoginWithOTP)
        .def("reqOrderInsert", &PyTdApi::reqOrderInsert)
        .def("reqParkedOrderInsert", &PyTdApi::reqParkedOrderInsert)
        .def("reqParkedOrderAction", &PyTdApi::reqParkedOrderAction)
        .def("reqOrderAction", &PyTdApi::reqOrderAction)
        .def("reqQueryMaxOrderVolume", &PyTdApi::reqQryMaxOrderVolume)
        .def("reqSettlementInfoConfirm", &PyTdApi::reqSettlementInfoConfirm)
        .def("reqRemoveParkedOrder", &PyTdApi::reqRemoveParkedOrder)
        .def("reqRemoveParkedOrderAction", &PyTdApi::reqRemoveParkedOrderAction)
        .def("reqExecOrderInsert", &PyTdApi::reqExecOrderInsert)
        .def("reqExecOrderAction", &PyTdApi::reqExecOrderAction)
        .def("reqForQuoteInsert", &PyTdApi::reqForQuoteInsert)
        .def("reqQuoteInsert", &PyTdApi::reqQuoteInsert)
        .def("reqQuoteAction", &PyTdApi::reqQuoteAction)
        .def("reqBatchOrderAction", &PyTdApi::reqBatchOrderAction)
        .def("reqOptionSelfCloseInsert", &PyTdApi::reqOptionSelfCloseInsert)
        .def("reqOptionSelfCloseAction", &PyTdApi::reqOptionSelfCloseAction)
        .def("reqCombActionInsert", &PyTdApi::reqCombActionInsert)
        .def("reqQryOrder", &PyTdApi::reqQryOrder)
        .def("reqQryTrade", &PyTdApi::reqQryTrade)
        .def("reqQryInvestorPosition", &PyTdApi::reqQryInvestorPosition)
        .def("reqQryTradingAccount", &PyTdApi::reqQryTradingAccount)
        .def("reqQryInvestor", &PyTdApi::reqQryInvestor)
        .def("reqQryTradingCode", &PyTdApi::reqQryTradingCode)
        .def("reqQryInstrumentMarginRate", &PyTdApi::reqQryInstrumentMarginRate)
        .def("reqQryInstrumentCommissionRate", &PyTdApi::reqQryInstrumentCommissionRate)
        .def("reqQryExchange", &PyTdApi::reqQryExchange)
        .def("reqQryProduct", &PyTdApi::reqQryProduct)
        .def("reqQryInstrument", &PyTdApi::reqQryInstrument)
        .def("reqQryDepthMarketData", &PyTdApi::reqQryDepthMarketData)
        .def("reqQrySettlementInfo", &PyTdApi::reqQrySettlementInfo)
        .def("reqQryTransferBank", &PyTdApi::reqQryTransferBank)
        .def("reqQryInvestorPositionDetail", &PyTdApi::reqQryInvestorPositionDetail)
        .def("reqQryNotice", &PyTdApi::reqQryNotice)
        .def("reqQrySettlementInfoConfirm", &PyTdApi::reqQrySettlementInfoConfirm)
        .def("reqQryInvestorPositionCombineDetail", &PyTdApi::reqQryInvestorPositionCombineDetail)
        .def("reqQryCFMMCTradingAccountKey", &PyTdApi::reqQryCFMMCTradingAccountKey)
        .def("reqQryEWarrantOffset", &PyTdApi::reqQryEWarrantOffset)
        .def("reqQryInvestorProductGroupMargin", &PyTdApi::reqQryInvestorProductGroupMargin)
        .def("reqQryExchangeMarginRate", &PyTdApi::reqQryExchangeMarginRate)
        .def("reqQryExchangeMarginRateAdjust", &PyTdApi::reqQryExchangeMarginRateAdjust)
        .def("reqQryExchangeRate", &PyTdApi::reqQryExchangeRate)
        .def("reqQrySecAgentACIDMap", &PyTdApi::reqQrySecAgentACIDMap)
        .def("reqQryProductExchRate", &PyTdApi::reqQryProductExchRate)
        .def("reqQryProductGroup", &PyTdApi::reqQryProductGroup)
        .def("reqQryMMInstrumentCommissionRate", &PyTdApi::reqQryMMInstrumentCommissionRate)
        .def("reqQryMMOptionInstrCommRate", &PyTdApi::reqQryMMOptionInstrCommRate)
        .def("reqQryInstrumentOrderCommRate", &PyTdApi::reqQryInstrumentOrderCommRate)
        .def("reqQrySecAgentTradingAccount", &PyTdApi::reqQrySecAgentTradingAccount)
        .def("reqQrySecAgentCheckMode", &PyTdApi::reqQrySecAgentCheckMode)
        .def("reqQrySecAgentTradeInfo", &PyTdApi::reqQrySecAgentTradeInfo)
        .def("reqQryOptionInstrTradeCost", &PyTdApi::reqQryOptionInstrTradeCost)
        .def("reqQryOptionInstrCommRate", &PyTdApi::reqQryOptionInstrCommRate)
        .def("reqQryExecOrder", &PyTdApi::reqQryExecOrder)
        .def("reqQryForQuote", &PyTdApi::reqQryForQuote)
        .def("reqQryQuote", &PyTdApi::reqQryQuote)
        .def("reqQryOptionSelfClose", &PyTdApi::reqQryOptionSelfClose)
        .def("reqQryInvestUnit", &PyTdApi::reqQryInvestUnit)
        .def("reqQryCombInstrumentGuard", &PyTdApi::reqQryCombInstrumentGuard)
        .def("reqQryCombAction", &PyTdApi::reqQryCombAction)
        .def("reqQryTransferSerial", &PyTdApi::reqQryTransferSerial)
        .def("reqQryAccountregister", &PyTdApi::reqQryAccountregister)
        .def("reqQryContractBank", &PyTdApi::reqQryContractBank)
        .def("reqQryParkedOrder", &PyTdApi::reqQryParkedOrder)
        .def("reqQryParkedOrderAction", &PyTdApi::reqQryParkedOrderAction)
        .def("reqQryTradingNotice", &PyTdApi::reqQryTradingNotice)
        .def("reqQryBrokerTradingParams", &PyTdApi::reqQryBrokerTradingParams)
        .def("reqQryBrokerTradingAlgos", &PyTdApi::reqQryBrokerTradingAlgos)
        .def("reqQueryCFMMCTradingAccountToken", &PyTdApi::reqQueryCFMMCTradingAccountToken)
        .def("reqFromBankToFutureByFuture", &PyTdApi::reqFromBankToFutureByFuture)
        .def("reqFromFutureToBankByFuture", &PyTdApi::reqFromFutureToBankByFuture)
        .def("reqQueryBankAccountMoneyByFuture", &PyTdApi::reqQueryBankAccountMoneyByFuture)

        .def("OnFrontConnected", &PyTdApi::OnFrontConnected)
        .def("OnFrontDisconnected", &PyTdApi::OnFrontDisconnected)
        .def("OnHeartBeatWarning", &PyTdApi::OnHeartBeatWarning)
        .def("OnRspAuthenticate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspAuthenticate))
        .def("OnRspUserLogin", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspUserLogin))
        .def("OnRspUserLogout", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspUserLogout))
        .def("OnRspUserPasswordUpdate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspUserPasswordUpdate))
        .def("OnRspTradingAccountPasswordUpdate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspTradingAccountPasswordUpdate))
        .def("OnRspUserAuthMethod", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspUserAuthMethod))
        .def("OnRspGenUserCaptcha", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspGenUserCaptcha))
        .def("OnRspGenUserText", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspGenUserText))
        .def("OnRspOrderInsert", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspOrderInsert))
        .def("OnRspParkedOrderInsert", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspParkedOrderInsert))
        .def("OnRspParkedOrderAction", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspParkedOrderAction))
        .def("OnRspOrderAction", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspOrderAction))
        .def("OnRspQueryMaxOrderVolume", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryMaxOrderVolume))
        .def("OnRspSettlementInfoConfirm", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspSettlementInfoConfirm))
        .def("OnRspRemoveParkedOrder", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspRemoveParkedOrder))
        .def("OnRspRemoveParkedOrderAction", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspRemoveParkedOrderAction))
        .def("OnRspExecOrderInsert", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspExecOrderInsert))
        .def("OnRspExecOrderAction", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspExecOrderAction))
        .def("OnRspForQuoteInsert", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspForQuoteInsert))
        .def("OnRspQuoteInsert", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQuoteInsert))
        .def("OnRspQuoteAction", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQuoteAction))
        .def("OnRspBatchOrderAction", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspBatchOrderAction))
        .def("OnRspOptionSelfCloseInsert", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspOptionSelfCloseInsert))
        .def("OnRspOptionSelfCloseAction", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspOptionSelfCloseAction))
        .def("OnRspCombActionInsert", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspCombActionInsert))
        .def("OnRspQryOrder", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryOrder))
        .def("OnRspQryTrade", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryTrade))
        .def("OnRspQryInvestorPosition", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInvestorPosition))
        .def("OnRspQryTradingAccount", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryTradingAccount))
        .def("OnRspQryInvestor", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInvestor))
        .def("OnRspQryTradingCode", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryTradingCode))
        .def("OnRspQryInstrumentMarginRate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInstrumentMarginRate))
        .def("OnRspQryInstrumentCommissionRate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInstrumentCommissionRate))
        .def("OnRspQryExchange", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryExchange))
        .def("OnRspQryProduct", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryProduct))
        .def("OnRspQryInstrument", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInstrument))
        .def("OnRspQryDepthMarketData", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryDepthMarketData))
        .def("OnRspQrySettlementInfo", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQrySettlementInfo))
        .def("OnRspQryTransferBank", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryTransferBank))
        .def("OnRspQryInvestorPositionDetail", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInvestorPositionDetail))
        .def("OnRspQryNotice", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryNotice))
        .def("OnRspQrySettlementInfoConfirm", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQrySettlementInfoConfirm))
        .def("OnRspQryInvestorPositionCombineDetail", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInvestorPositionCombineDetail))
        .def("OnRspQryCFMMCTradingAccountKey", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryCFMMCTradingAccountKey))
        .def("OnRspQryEWarrantOffset", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryEWarrantOffset))
        .def("OnRspQryInvestorProductGroupMargin", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInvestorProductGroupMargin))
        .def("OnRspQryExchangeMarginRate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryExchangeMarginRate))
        .def("OnRspQryExchangeMarginRateAdjust", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryExchangeMarginRateAdjust))
        .def("OnRspQryExchangeRate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryExchangeRate))
        .def("OnRspQrySecAgentACIDMap", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQrySecAgentACIDMap))
        .def("OnRspQryProductExchRate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryProductExchRate))
        .def("OnRspQryProductGroup", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryProductGroup))
        .def("OnRspQryMMInstrumentCommissionRate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryMMInstrumentCommissionRate))
        .def("OnRspQryMMOptionInstrCommRate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryMMOptionInstrCommRate))
        .def("OnRspQryInstrumentOrderCommRate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInstrumentOrderCommRate))
        .def("OnRspQrySecAgentTradingAccount", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQrySecAgentTradingAccount))
        .def("OnRspQrySecAgentCheckMode", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQrySecAgentCheckMode))
        .def("OnRspQrySecAgentTradeInfo", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQrySecAgentTradeInfo))
        .def("OnRspQryOptionInstrTradeCost", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryOptionInstrTradeCost))
        .def("OnRspQryOptionInstrCommRate", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryOptionInstrCommRate))
        .def("OnRspQryExecOrder", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryExecOrder))
        .def("OnRspQryForQuote", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryForQuote))
        .def("OnRspQryQuote", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryQuote))
        .def("OnRspQryOptionSelfClose", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryOptionSelfClose))
        .def("OnRspQryInvestUnit", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryInvestUnit))
        .def("OnRspQryCombInstrumentGuard", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryCombInstrumentGuard))
        .def("OnRspQryCombAction", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryCombAction))
        .def("OnRspQryTransferSerial", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryTransferSerial))
        .def("OnRspQryAccountregister", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryAccountregister))
        .def("OnRspError", py::overload_cast<const py::dict &, int, bool>(&PyTdApi::OnRspError))
        .def("OnRtnOrder", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnOrder))
        .def("OnRtnTrade", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnTrade))
        .def("OnErrRtnOrderInsert", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnOrderInsert))
        .def("OnErrRtnOrderAction", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnOrderAction))
        .def("OnRtnInstrumentStatus", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnInstrumentStatus))
        .def("OnRtnBulletin", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnBulletin))
        .def("OnRtnTradingNotice", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnTradingNotice))
        .def("OnRtnErrorConditionalOrder", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnErrorConditionalOrder))
        .def("OnRtnExecOrder", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnExecOrder))
        .def("OnErrRtnExecOrderInsert", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnExecOrderInsert))
        .def("OnErrRtnExecOrderAction", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnExecOrderAction))
        .def("OnErrRtnForQuoteInsert", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnForQuoteInsert))
        .def("OnRtnQuote", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnQuote))
        .def("OnErrRtnQuoteInsert", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnQuoteInsert))
        .def("OnErrRtnQuoteAction", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnQuoteAction))
        .def("OnRtnForQuoteRsp", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnForQuoteRsp))
        .def("OnRtnCFMMCTradingAccountToken", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnCFMMCTradingAccountToken))
        .def("OnErrRtnBatchOrderAction", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnBatchOrderAction))
        .def("OnRtnOptionSelfClose", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnOptionSelfClose))
        .def("OnErrRtnOptionSelfCloseInsert", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnOptionSelfCloseInsert))
        .def("OnErrRtnOptionSelfCloseAction", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnOptionSelfCloseAction))
        .def("OnRtnCombAction", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnCombAction))
        .def("OnErrRtnCombActionInsert", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnCombActionInsert))
        .def("OnRspQryContractBank", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryContractBank))
        .def("OnRspQryParkedOrder", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryParkedOrder))
        .def("OnRspQryParkedOrderAction", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryParkedOrderAction))
        .def("OnRspQryTradingNotice", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryTradingNotice))
        .def("OnRspQryBrokerTradingParams", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryBrokerTradingParams))
        .def("OnRspQryBrokerTradingAlgos", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQryBrokerTradingAlgos))
        .def("OnRspQueryCFMMCTradingAccountToken", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQueryCFMMCTradingAccountToken))
        .def("OnRtnFromBankToFutureByBank", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnFromBankToFutureByBank))
        .def("OnRtnFromFutureToBankByBank", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnFromFutureToBankByBank))
        .def("OnRtnRepealFromBankToFutureByBank", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnRepealFromBankToFutureByBank))
        .def("OnRtnRepealFromFutureToBankByBank", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnRepealFromFutureToBankByBank))
        .def("OnRtnFromBankToFutureByFuture", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnFromBankToFutureByFuture))
        .def("OnRtnFromFutureToBankByFuture", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnFromFutureToBankByFuture))
        .def("OnRtnRepealFromBankToFutureByFutureManual", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnRepealFromBankToFutureByFutureManual))
        .def("OnRtnRepealFromFutureToBankByFutureManual", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnRepealFromFutureToBankByFutureManual))
        .def("OnRtnQueryBankBalanceByFuture", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnQueryBankBalanceByFuture))
        .def("OnErrRtnBankToFutureByFuture", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnBankToFutureByFuture))
        .def("OnErrRtnFutureToBankByFuture", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnFutureToBankByFuture))
        .def("OnErrRtnRepealBankToFutureByFutureManual", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnRepealBankToFutureByFutureManual))
        .def("OnErrRtnRepealFutureToBankByFutureManual", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnRepealFutureToBankByFutureManual))
        .def("OnErrRtnQueryBankBalanceByFuture", py::overload_cast<const py::dict &, const py::dict &>(&PyTdApi::OnErrRtnQueryBankBalanceByFuture))
        .def("OnRtnRepealFromBankToFutureByFuture", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnRepealFromBankToFutureByFuture))
        .def("OnRtnRepealFromFutureToBankByFuture", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnRepealFromFutureToBankByFuture))
        .def("OnRspFromBankToFutureByFuture", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspFromBankToFutureByFuture))
        .def("OnRspFromFutureToBankByFuture", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspFromFutureToBankByFuture))
        .def("OnRspQueryBankAccountMoneyByFuture", py::overload_cast<const py::dict &, const py::dict &, int, bool>(&PyTdApi::OnRspQueryBankAccountMoneyByFuture))
        .def("OnRtnOpenAccountByBank", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnOpenAccountByBank))
        .def("OnRtnCancelAccountByBank", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnCancelAccountByBank))
        .def("OnRtnChangeAccountByBank", py::overload_cast<const py::dict &>(&PyTdApi::OnRtnChangeAccountByBank));
}
